"""initial_schema

Revision ID: c617a5efbe23
Revises:
Create Date: 2026-02-22 17:57:57.794326

"""

from typing import Sequence, Union

import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c617a5efbe23"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create base tables first
    op.create_table(
        "contacts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.Column("contact_handle", sa.String(length=255), nullable=False),
        sa.Column("contact_name", sa.String(length=200), nullable=False),
        sa.Column("platform", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "owner_id", "contact_handle", "platform", name="uq_owner_contact_handle"
        ),
    )
    op.create_index(
        op.f("ix_contacts_contact_handle"), "contacts", ["contact_handle"], unique=False
    )
    op.create_index(
        op.f("ix_contacts_owner_id"), "contacts", ["owner_id"], unique=False
    )

    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("platform", sa.String(length=50), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("from_contact_id", sa.Integer(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["from_contact_id"], ["contacts.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_messages_chat_id"), "messages", ["chat_id"], unique=False)
    op.create_index(
        op.f("ix_messages_from_contact_id"),
        "messages",
        ["from_contact_id"],
        unique=False,
    )

    op.create_table(
        "summaries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("contact_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("summary_text", sa.Text(), nullable=False),
        sa.Column("embedding", Vector(768), nullable=True),
        sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_summaries_contact_id"), "summaries", ["contact_id"], unique=False
    )

    op.create_table(
        "relationships",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("contact_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("contact_id"),
    )

    op.create_table(
        "habits",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.Column("trigger", sa.String(length=200), nullable=False),
        sa.Column("frequency", sa.Float(), nullable=False),
        sa.Column("correlation", sa.Float(), nullable=False),
        sa.Column("last_detected", sa.DateTime(timezone=True), nullable=True),
        sa.Column("suggestion", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_habits_owner_id"), "habits", ["owner_id"], unique=False)

    op.create_table(
        "semantic_memories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.Column("contact_id", sa.Integer(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", Vector(768), nullable=False),
        sa.Column("importance", sa.SmallInteger(), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default="{}",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "content_search",
            postgresql.TSVECTOR,
            sa.Computed("to_tsvector('english', content)", persisted=True),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_semantic_memories_contact_id"),
        "semantic_memories",
        ["contact_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_semantic_memories_owner_id"),
        "semantic_memories",
        ["owner_id"],
        unique=False,
    )

    op.create_table(
        "owner_memories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", Vector(768), nullable=False),
        sa.Column("importance", sa.SmallInteger(), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default="{}",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "content_search",
            postgresql.TSVECTOR,
            sa.Computed("to_tsvector('english', content)", persisted=True),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_owner_memories_owner_id"), "owner_memories", ["owner_id"], unique=False
    )

    op.create_table(
        "scheduled_jobs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.String(length=32), nullable=False),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("delay_minutes", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("fire_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("executed", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scheduled_jobs_job_id"), "scheduled_jobs", ["job_id"], unique=True
    )
    op.create_index(
        op.f("ix_scheduled_jobs_owner_id"), "scheduled_jobs", ["owner_id"], unique=False
    )
    op.create_table(
        "user_states",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("mood", sa.String(length=50), nullable=False),
        sa.Column("last_active", sa.DateTime(timezone=True), nullable=True),
        sa.Column("message_count_today", sa.Integer(), nullable=False),
        sa.Column("streak_days", sa.Integer(), nullable=False),
        sa.Column("last_streak_date", sa.Date(), nullable=True),
        sa.Column(
            "extra",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_states_user_id"), "user_states", ["user_id"], unique=True
    )

    # Now create tables that depend on contacts
    op.create_table(
        "contact_states",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.Column("contact_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("message_count", sa.Integer(), nullable=False),
        sa.Column("mood", sa.String(length=50), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "contact_id", name="uq_owner_contact_state"),
    )
    op.create_index(
        op.f("ix_contact_states_contact_id"),
        "contact_states",
        ["contact_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contact_states_owner_id"), "contact_states", ["owner_id"], unique=False
    )
    op.create_table(
        "mood_entries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.Column("contact_id", sa.Integer(), nullable=True),
        sa.Column("mood", sa.String(length=50), nullable=False),
        sa.Column("valence", sa.Float(), nullable=False),
        sa.Column("message_snippet", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_mood_entries_contact_id"), "mood_entries", ["contact_id"], unique=False
    )
    op.create_index(
        op.f("ix_mood_entries_owner_id"), "mood_entries", ["owner_id"], unique=False
    )
    op.create_table(
        "relationship_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("contact_id", sa.Integer(), nullable=False),
        sa.Column("score_before", sa.Integer(), nullable=False),
        sa.Column("score_after", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_relationship_events_contact_id"),
        "relationship_events",
        ["contact_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop dependent tables first
    op.drop_index(
        op.f("ix_relationship_events_contact_id"), table_name="relationship_events"
    )
    op.drop_table("relationship_events")
    op.drop_index(op.f("ix_mood_entries_owner_id"), table_name="mood_entries")
    op.drop_index(op.f("ix_mood_entries_contact_id"), table_name="mood_entries")
    op.drop_table("mood_entries")
    op.drop_index(op.f("ix_contact_states_owner_id"), table_name="contact_states")
    op.drop_index(op.f("ix_contact_states_contact_id"), table_name="contact_states")
    op.drop_table("contact_states")
    op.drop_index(op.f("ix_user_states_user_id"), table_name="user_states")
    op.drop_table("user_states")
    op.drop_index(op.f("ix_scheduled_jobs_owner_id"), table_name="scheduled_jobs")
    op.drop_index(op.f("ix_scheduled_jobs_job_id"), table_name="scheduled_jobs")
    op.drop_table("scheduled_jobs")
    op.drop_index(op.f("ix_owner_memories_owner_id"), table_name="owner_memories")
    op.drop_table("owner_memories")
    op.drop_index(op.f("ix_semantic_memories_owner_id"), table_name="semantic_memories")
    op.drop_index(
        op.f("ix_semantic_memories_contact_id"), table_name="semantic_memories"
    )
    op.drop_table("semantic_memories")
    op.drop_index(op.f("ix_habits_owner_id"), table_name="habits")
    op.drop_table("habits")

    # Drop base tables
    op.drop_table("relationships")
    op.drop_index(op.f("ix_summaries_contact_id"), table_name="summaries")
    op.drop_table("summaries")
    op.drop_index(op.f("ix_messages_from_contact_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_chat_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_contacts_owner_id"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_contact_handle"), table_name="contacts")
    op.drop_table("contacts")
    # ### end Alembic commands ###
    # ### end Alembic commands ###
